name: "Run tests"

on:
  push:
  workflow_call:

jobs:
  test:
    name: Pest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo, mysql
          coverage: none

      - name: Install dependencies
        run: |
          composer install

      - name: Execute tests
        run: vendor/bin/pest
