name: "Run tests"

on:
  push:
  workflow_call:

jobs:
  test:
    name: Pest
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest]
        php: [8.0, 8.1]
        stability: [prefer-lowest, prefer-stable]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo, mysql
          coverage: none

      - name: Install dependencies
        run: |
          composer install --${{ matrix.stability }}

      - name: Execute tests
        run: vendor/bin/pest
